### ISSUE TITLE
Support for templated or recurring countdown

### ISSUE THREAD

**Issue by robison** [grafana/clock-panel#10]
Would it be possible to either support templating or recurring countdowns? The biggest use case I could think of is recurring deadlines for things like deploy windows, on a day-over-day basis. I'll be more than happy to make an attempt at it if there seems to be any interest.

**Comment by daniellee** [comment]
Sounds interesting. Can you elaborate a bit more on the templating and recurring countdowns? How would that work?

**Comment by robison** [comment]
For example, deploy windows - say a company has two deadlines daily for deploys, 10am & 4pm. It'd be great if one could configure the deadline as recurring, such that it always counted down the time remaining to the next configured recurring deadline. Does that make sense?

**Comment by daniellee** [comment]
Ah, now I understand. Sounds like a good idea.

**Comment by johnseekins** [comment]
:+1:
