### ISSUE TITLE
Support loop countdown

### ISSUE THREAD

**Issue by jdloft** [grafana/clock-panel#13]
The ability to countdown to a specific time in a loop (after it occurs, reset for the next occurrence) would be helpful. This could possibly be attained by allowing times values to be left out to denote a wildcard. For example, if I specify a panel to countdown to 19:56:00 but don't specify a day, the panel would countdown to 19:56 and would then reset and countdown to 19:56 the next day.

**Comment by mvadu** [comment]
+1 This is specially helpful when you have a dashboard with Auto refresh (say every 5 min), and you want to show how long is left to next refresh cycle.

**Comment by alfiepates** [comment]
We have a regular tuesday event and adding a countdown to that event to the playlist we have on our digital signage would be really useful. :+1:

**Comment by hidesoon** [comment]
and for production shift or cycle time, e.g cycle time is 2 hour, I can show still got how many time to finish the current task
