### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by xMadNet** [grafana/clock-panel#133]
Hi,
Grafana 9.4.7 on raspberry pi (Linux TELEINFO 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux)
I have installed plugin with : sudo grafana-cli plugins install grafana-clock-panel
I have restarted grafana : sudo systemctl restart grafana-server
system clt says : Apr 09 11:42:06 TELEINFO grafana[10322]: logger=plugin.loader t=2023-04-09T11:42:06.531516612+02:00 level=info msg="Plugin registered" pluginID=grafana-clock-panel
In grafana : I can see clock in Plugins UI. It is declared as Signed but no Install. Install button said "Plugin already installed"
BUT
I can't see clock plug in Panel with other PlugIns

Is in an issue ?

BR

**Comment by jackw** [comment]
@xMadNet thanks for reporting this issue. I'm unaware of any current known issues with install the clock-panel specifically. 

Does this happen only with clock-panel or all plugins installed via grafana-cli? 

Do you see any error messages like "plugin failed to load"? Do you see any errors in the browser developer tools console tab? If you open your browser developer tools and inspect the network tab do you see the clock-panel `module.js` loading?

I've also noticed you're using sudo to install the plugin. Perhaps this is a permissions issue?

**Comment by academo** [comment]
Closing this stale issue to reduce backlog. @xMadNet please check Jacks suggestions and re-open this issue if you want to follow up and still experiment this issue.
