### ISSUE TITLE
[FeatureRequest] New time zone option to follow dashboard's time zone selection

### ISSUE THREAD

**Issue by VictorColomb** [grafana/clock-panel#135]
To allow all dates and times on a dashboard to sync up, it would be nice for the clock to be able to follow the time zone selected in the dashboard's datetime picker.

<img width="280" alt="Screenshot 2023-04-17 150754" src="https://user-images.githubusercontent.com/51762123/232493279-45fc9112-8685-4495-bf51-6771506d7d63.png">

**Comment by tolzhabayev** [comment]
Internal reference on how to possibly achieve: https://github.com/grafana/grafana/issues/64400
