### ISSUE TITLE
Support: StopWatch Count Up with display in DD:HH Feature Request

### ISSUE THREAD

**Issue by roscoe57** [grafana/clock-panel#14]
Feature Request 

just tried the CLOCK plugin

would be cool to have a Timer count up feature and have the display formatable for DD:HH
(it has a Countdown but no Stopwatch/timer) i.e. how long something has been going on.

**Comment by jareware** [comment]
Would also be interested in this! Are PR's welcome?

**Comment by daniellee** [comment]
Yes, a PR for this would be welcome.

**Comment by coccobill1** [comment]
Any updates? People need their quarantine counters.

**Comment by jimdevops19** [comment]
Leaving this for an update on that aswell

**Comment by Bodypull** [comment]
Would love this feature too. Option for counting up instead of only a static Countdown End Text.

**Comment by nabelekt** [comment]
Agree that counting up is desired.

**Comment by ollie-campbell** [comment]
+1 from me.

**Comment by OttoLeirer** [comment]
news

**Comment by pslestang** [comment]
Here the PR that implements the countup https://github.com/grafana/clock-panel/pull/101
