### ISSUE TITLE
while creating plugin,i will get error like..Plugin Error

### ISSUE THREAD

**Issue by yuvaraj951** [grafana/clock-panel#16]
Plugin Error
Error: XHR error (404 Not Found) loading http://localhost:3000/public/traceur?bust=1476854915426 Error loading http://localhost:3000/public/traceur Error loading http://localhost:3000/public/plugins/grafana-processline-panel/module.js

please help me out!!!!!

**Comment by daniellee** [comment]
Are you writing a new plugin called grafana-processline-panel?
