### ISSUE TITLE
Add D:HH:mm time format for countdown.

### ISSUE THREAD

**Issue by vaivars** [grafana/clock-panel#18]
Currently the countdown selection offers only the usage of the "worded" time format. X days X hours etc. left, while for the actual TIME selection, you can have 1d:11h:11m:11s option.

Please add support for the numerical format.

**Comment by koallen** [comment]
I'm having the same problem too. Why does the screenshot provided in the README has all the features?

**Comment by jareware** [comment]
@daniellee would you have a sec to take a look at my PR for fixing this? Would love to have this on our wall already. ;)

**Comment by RickyLam11** [comment]
I tried use "D:HH:mm" or other https://momentjs.com/docs/#/customization/relative-time/ format in the `countdownSettings.customFormat`, but I still get an "Incorrect locale information provided". Any idea ?
