### ISSUE TITLE
Bug: New Query Option - Query Editor does now show up on updates

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/clock-panel#187]
The query editor does not show up if plugin is updated let's say from `2.1.3` to `2.1.5`.

Reproduction steps:
- Install 2.1.3 version, create a dashboard, save it
- Update
- Try to edit the panel

Expected:
- Query editor shows up

Actual:
- No query editor visible

**Comment by academo** [comment]
This is now fixed with the latest 2.1.6 release.
