### ISSUE TITLE
Error "Missing panel reference ID"

### ISSUE THREAD

**Issue by I-am-a-node** [grafana/clock-panel#189]
New Error.
 Plugin version I have installed is 2.1.6 

There is a new error that appears on the Error Tab. "Missing panel reference ID".
Also shown on the dash frontend view in the upper left corner as a red mark.

Also I am getting data source errors?!?! This plugin dont need a data source!? Or, am I missing something? Is it new?

**Comment by briangann** [comment]
it's a new option and i think it needs a migration method added to prevent these errors.  for now you can edit the panel and select '---Grafana---' as the datasource and save, the error will go away.

**Comment by I-am-a-node** [comment]
> it's a new option and i think it needs a migration method added to prevent these errors. for now you can edit the panel and select '---Grafana---' as the datasource and save, the error will go away.

@briangann Thanks Bryan. 
Feedback; I went for your suggestion selecting '---Grafana---' as the datasource. The ! triangle on the visualization is gone. However still having the other error, popup to the right on the dashboard "Failed to retrieve datasource. Datasource screensaverclock was not found" appears everytime the page is loading. 

![Screenshot 2024-06-03 at 12 28 48](https://github.com/grafana/clock-panel/assets/101867514/072b3187-219c-41d0-9fe3-11967c696058)

Hope this can be useful.

**Comment by tolzhabayev** [comment]
Can you share the panel with us like this: https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

Bute before sending, remove any sensitive data you might have.

**Comment by I-am-a-node** [comment]
@tolzhabayev @briangann Sorry for the delay. Dont waste any more time on this.
 I will re-create new dashboards, annoying and time consuming. Should not have to be the case after an update.

However, please close this ticket and lets move on.
Thanks or taking your time.

**Comment by briangann** [comment]
Sorry about the upgrade going sideways, v2.1.7 is about to be released and will fix this issue in case you haven't already recreated the dashboards.

**Comment by briangann** [comment]
fixed by #192
