### ISSUE TITLE
Multiple countdown clocks in one row share the same deadline

### ISSUE THREAD

**Issue by macieklukasik88** [grafana/clock-panel#20]
When I try to add 3 countdown clocks in one dashboard row with different deadlines
Then the same deadline is set for all three clocks

**Comment by bmagistro** [comment]
Bug can be expanded to multiple countdowns on a panel.  Calling duplicate breaks it up as does saving the panel at which point different end times can be set on each.

**Comment by daniellee** [comment]
Thanks @bmagistro for that extra info that helped me recreate the problem.

**Comment by daniellee** [comment]
Published a new version 0.0.9 with a fix for this.
