### ISSUE TITLE
Warning received under v2.1.7

### ISSUE THREAD

**Issue by Rushmed** [grafana/clock-panel#200]
Hi.

After updating the plugin to 2.1.7 I got red triangles in Grafan mith message "InfluxDB returned error: &{0x6042b00 0x4002c90c00 0x60b8c80}".
The shown values are correct but how to get rid of the warning?
![image](https://github.com/grafana/clock-panel/assets/59259796/d5a6282d-9f12-4655-a23e-919e7fe3b2cc)

![image](https://github.com/grafana/clock-panel/assets/59259796/18670e74-b95b-4b08-95ab-79839b0b426f)

Deleting the measurement does not help.

**Comment by briangann** [comment]
The quickest fix would be to delete the query from the panel.

The modifications made to migrations can't tell if the query is intentional or not.

**Comment by briangann** [comment]
let us investigate this as it should not be happening for new panels, and saving after deleting the query should have fix it.

**Comment by Rushmed** [comment]
Ok how can I support?

**Comment by briangann** [comment]
Which version of Grafana are you using? I'll test it using that version to replicate the problem.  It looks like you have influx as your default datasource also.

**Comment by Rushmed** [comment]
Grafana v11.1.0 (5b85c4c2fc)

**Comment by briangann** [comment]
Taking a closer look at this, it appears that the migration detection isn't working as intended.  I have reproduced this when the default datasource is not "test data"
