### ISSUE TITLE
Getting _.defaultsDeep is not a function

### ISSUE THREAD

**Issue by robbyk11** [grafana/clock-panel#24]
Get this error every time we try to add a clock panel to a graph.  THought the last release might solve it, but no luck.  any idea?

**Comment by daniellee** [comment]
What version of grafana are you using? The latest versions of Grafana upgraded Lodash which allowed me to fix this [bug](https://github.com/grafana/clock-panel/issues/20). 

This is similar to #23

**Comment by robbyk11** [comment]
3.1.1   Thanks.  will upgrade and try the latest.
