### ISSUE TITLE
Plugin Error _.defaultsDeep is not a function

### ISSUE THREAD

**Issue by ChaitDevOps** [grafana/clock-panel#25]
Installed clock plugin with CLI and restarted grafana-server.  
when i go to add the panel, the error `Plugin Error
_.defaultsDeep is not a function` shows up. Can someone please help me?

https://grafana.com/plugins/grafana-clock-panel/installation
Latest Version of plugin installed.

**Comment by ChaitDevOps** [comment]
Looks like Version 0.0.8 has issue. I downgraded to lower version and it works now.

**Comment by daniellee** [comment]
Dupe. See #24 and #23 

Upgrade your Grafana is the short answer.
