### ISSUE TITLE
Update build instructions in readme

### ISSUE THREAD

**Issue by 7yl4r** [grafana/clock-panel#34]
Following Development instructions in the readme on step 5:

```
tylar@tylardesk:~/clock-panel$ grunt watch
A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile.
```

This is a reasonable error since there is no `grunt.js` or `grunfile.js` in this repository.
Maybe one needs to be added, or can the latest grunt pull from `package.json` (I'm using `grunt-cli v1.3.2`)?

I was able to get working by replacing this step with `npm install .` and `npm run watch` instead.

It looks like grunt was dropped in favor of webpack recently, but the readme needs to be updated?

**Comment by marefr** [comment]
Yes, you're correct. It's been converted to typescript and webpack. Thanks for the pointer.

**Comment by daniellee** [comment]
Thanks - was just about to go back and update the instructions.
