### ISSUE TITLE
Can't change Clock and Date text font size.

### ISSUE THREAD

**Issue by lucavignali** [grafana/clock-panel#36]
I have Grafana v5.2.1 installed. I have installed the grafana-clock-panel v1.0.0 which works correctly. However, even if I change Font Size in the Options/Time format panel, the actual size of the time in the panel doesn't change. Same problem with Font Size of the Date.

I am basically changing the standard 60px in to 20px in the Time format but the size of the time doesn't change.

![cattura](https://user-images.githubusercontent.com/7933169/49167492-c2187880-f335-11e8-9ed1-4ce35d01d636.JPG)

**Comment by daniellee** [comment]
I just tested this with 5.2.1 using this docker run:

`docker run -p 3000:3000 -e "GF_INSTALL_PLUGINS=grafana-clock-panel" grafana/grafana:5.2.1`

And it seems to work fine in Chrome and Firefox on Linux:

![image](https://user-images.githubusercontent.com/434655/49429301-75ef8d00-f7a8-11e8-8c3b-5ab14f4d3307.png)

Which browser and OS are you using? And does it work if you save the dashboard and refresh the page?

**Comment by lucavignali** [comment]
Yes, I confirm that clock panel works with Chrome. But it doesn't work with Internet Explorer.

**Comment by GarbatyGrabarz** [comment]
Changing font size gives no effect
Tried with Clock 2.0.0 with Grafana 8.5.4 in Chrome and Edge

**Comment by bskrt** [comment]
Had the same issue but managed to fix it.
If you just define a unit in the font size field, it does work:
e.g. 120px or 4rem (or any other CSS supported unit for that matter)

I can't remember exactly if the field had a unit after initial installation, but that's something to look at.

**Comment by GarbatyGrabarz** [comment]
It worked, thanks! Currently the field says "date format" when empty. Maybe a hint there?

**Comment by bskrt** [comment]
Glad it helped! Sure you don't have custom clock format selected?

**Comment by GarbatyGrabarz** [comment]
Yeap. Besides, this text is in the "Font size" field and appears in all three modes: 24 Hour, 12 Hour, Custom
