### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by rekcah78** [grafana/clock-panel#4]
Hi,

When i try to upgrade the plugin,i get this error:
(Version 3.0.0-beta2)

[root@grafana] /home/noc> grafana-cli plugins upgrade-all                                                                             
Upgrading alexanderzobnin-zabbix-app 
Removing plugin: alexanderzobnin-zabbix-app
installing alexanderzobnin-zabbix-app @ 3.0.0-beta5
from url: https://grafana.net/api/plugins/alexanderzobnin-zabbix-app/versions/3.0.0-beta5/download
into: /var/lib/grafana/plugins

✔ Installed alexanderzobnin-zabbix-app successfully 
Upgrading grafana-clock-panel 
Removing plugin: grafana-clock-panel
installing grafana-clock-panel @ 0.0.6
from url: https://grafana.net/api/plugins/grafana-clock-panel/versions/0.0.6/download
into: /var/lib/grafana/plugins

panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.downloadFile.func1(0xc820504340, 0x13, 0xc820504c00, 0x18, 0xc820394050, 0x4b)
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/install_command.go:132 +0x1c4
archive/zip.readDirectoryEnd(0x7f6fb807c0d8, 0xc820381e00, 0xffffffffffffffff, 0x7f6fba9010d0, 0x0, 0x0)
	/usr/local/go/src/archive/zip/reader.go:348 +0xfe
archive/zip.(*Reader).init(0xc82031ae00, 0x7f6fb807c0d8, 0xc820381e00, 0xffffffffffffffff, 0x0, 0x0)
	/usr/local/go/src/archive/zip/reader.go:77 +0x5f
archive/zip.NewReader(0x7f6fb807c0d8, 0xc820381e00, 0xffffffffffffffff, 0xf850b, 0x0, 0x0)
	/usr/local/go/src/archive/zip/reader.go:70 +0x64
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.downloadFile(0xc820504340, 0x13, 0xc820504c00, 0x18, 0xc820394050, 0x4b, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/install_command.go:148 +0x2fe
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.InstallPlugin(0xc82000ffa0, 0x13, 0xc820482720, 0x5, 0x7f6fbc1488e0, 0xc82003c048, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/install_command.go:86 +0x9bb
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.upgradeAllCommand(0x7f6fbc1488e0, 0xc82003c048, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/upgrade_all_command.go:57 +0x6a6
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.runCommand.func1(0xc820096ea0)
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/commands.go:13 +0xa2
github.com/codegangsta/cli.Command.Run(0x821990, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x87bbe0, 0x23, 0x0, ...)
	/go/src/github.com/grafana/grafana/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:137 +0x107e
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc820096c60, 0xc820096b40, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:283 +0x11a0
github.com/codegangsta/cli.Command.startApp(0x8126a8, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x85d440, 0x1a, 0x0, ...)
	/go/src/github.com/grafana/grafana/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:215 +0x7cc
github.com/codegangsta/cli.Command.Run(0x8126a8, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x85d440, 0x1a, 0x0, ...)
	/go/src/github.com/grafana/grafana/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:59 +0x197d
github.com/codegangsta/cli.(*App).Run(0xc820096a20, 0xc82000a1b0, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:176 +0xfff
main.main()
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/main.go:55 +0x4d6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 11 [select]:
net/http.(*persistConn).readLoop(0xc8200c00b0)
	/usr/local/go/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc8200c00b0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 55 [select]:
net/http.(*persistConn).readLoop(0xc82044c0b0)
	/usr/local/go/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 22 [select]:
net/http.(*persistConn).readLoop(0xc82044c000)
	/usr/local/go/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 23 [select]:
net/http.(*persistConn).writeLoop(0xc82044c000)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 39 [IO wait]:
net.runtime_pollWait(0x7f6fbc149b88, 0x72, 0xc8200101d0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8204a4290, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204a4290, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8204a4230, 0xc8204f4400, 0x400, 0x400, 0x0, 0x7f6fbc144050, 0xc8200101d0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8204d2020, 0xc8204f4400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8204675f0, 0x7f6fbc149e88, 0xc8204d2020, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8204ac2c0, 0x8b9317, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8204ac2c0, 0xc82052a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7f6fbc152838, 0xc8204ac2c0, 0xc8204de058, 0xc82052a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82050acc0, 0xc82052a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82046acc0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82046acc0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8204de000)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 40 [select]:
net/http.(*persistConn).writeLoop(0xc8204de000)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 52 [IO wait]:
net.runtime_pollWait(0x7f6fbc149888, 0x72, 0xc8200101d0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200ff9c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200ff9c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200ff960, 0xc82049f000, 0x1000, 0x1000, 0x0, 0x7f6fbc144050, 0xc8200101d0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8204d2038, 0xc82049f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820479ad0, 0x7f6fbc149e88, 0xc8204d2038, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8204ac580, 0x8b9317, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8204ac580, 0xc820448000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7f6fbc152838, 0xc8204ac580, 0xc82044c528, 0xc820448000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8203e2400, 0xc820448000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82020e420)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82020e420, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82044c4d0)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 53 [select]:
net/http.(*persistConn).writeLoop(0xc82044c4d0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 56 [select]:
net/http.(*persistConn).writeLoop(0xc82044c0b0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

i fix my problem with
[root@grafana] ~noc> grafana-cli plugins install grafana-clock-panel                                                                  
installing grafana-clock-panel @ 0.0.6
from url: https://grafana.net/api/plugins/grafana-clock-panel/versions/0.0.6/download
into: /var/lib/grafana/plugins

✔ Installed grafana-clock-panel successfully 

the plugin working again.

**Comment by daniellee** [comment]
Thanks for letting me know. I will test the upgrade path and see if i can find something.
