### ISSUE TITLE
Timezone for Chennai Missing (IST GMT +5:30)

### ISSUE THREAD

**Issue by raidsec** [grafana/clock-panel#53]
Hello,

it looks like that the Timezone selection is missing IST +5:30. And the manual offset function is not existing anymore.

Regards
raidsec

**Comment by lleixat** [comment]
Hi,
It seems you can select `Asia/Calcutta` which is +5:30 IST

Regards

**Comment by shavonn** [comment]
Closing this issue as @lleixat stated above, Asia/Calcutta covers this zone.

**Comment by slim-bean** [comment]
I'm not sure the effort to actually get IST as a choice from the dropdown? I spent a good chunk of time trying to figure this out today and finally resorted to searching closed issues figuring someone must have asked this.

Or as an alternative can we just put this in the docs so it's more obvious?
