### ISSUE TITLE
Problem with timezone offset

### ISSUE THREAD

**Issue by mrclramos** [grafana/clock-panel#58]
Hello,

Where the Clock plugin gets its tzdata information? My timezone (America/Sao_Paulo) does not have DST anymore, and it is at GMT -3, but after selecting the timezone on the dropbox, it shows GMT -02 (like when we used to have DST).

The system running the Grafana Server is updated with the latest tzdata information, and my workstation is also with the expected date/time.

I did not find any tzdata information on the code, so where is the tzdata information coming from?

**Comment by emersonramos** [comment]
I have the same problem. Any solution?
