### ISSUE TITLE
load external SVG to dashboard

### ISSUE THREAD

**Issue by GameOfThrow** [grafana/clock-panel#6]
Is there a way I could load a bunch of external SVGs into a Dashboard? I have some none-time-serie charts which I cannot generate using Grafana. I would ideally like to keep everything together (but in separate Dashboards)

**Comment by daniellee** [comment]
I think you're looking for the inbuilt text panel in Grafana. You can link to images in markdown like in the screenshot below or just write img tags in html mode. As this doesn't seem to be about the clock panel, I'm closing the issue. If I'm wrong let me know and I'll reopen it.

![textpanelscreenshot](https://cloud.githubusercontent.com/assets/434655/14734746/d30c267a-086c-11e6-98a3-23f190e36340.png)
