### ISSUE TITLE
Text is not centered when using a custom format with countdown

### ISSUE THREAD

**Issue by bp32795** [grafana/clock-panel#60]
When using a custom time format, the text becomes right-aligned in the panel, instead of centered. It is possible I am missing a setting within momentjs formatting, but I have not been able to find anything to center text. My custom format is `[❄]d[:]h[:]m[:]s[ until Holiday Shutdown❄]`. This is what it shows:
![image](https://user-images.githubusercontent.com/35607465/70070347-12658e80-15b9-11ea-91a2-19505d2f5d6d.png)

**Comment by srclosson** [comment]
Questions that need to be answered on investigation:

1. Does the clock panel have an option to enforce centering? 
2. If so, is that setting being honored correctly? If not, we should fix.

Another idea would be to allow custom CSS formatting? That could potentially override the panel layout?

**Comment by senfomat** [comment]
This problem occures, when the size of the panel is too small for the text. Fix in fd972334664b0787dcec894a307d397938f17c89
