### ISSUE TITLE
Panel background color is always black in Grafana 6.7.x

### ISSUE THREAD

**Issue by aadamovich** [grafana/clock-panel#66]
Just upgraded from Grafana 6.5.3 to 6.70 and then to 6.7.1 and background color is not shown anymore for any of the clock panels.

**Comment by therealcodlord** [comment]
+1 for this issue, thought I was doing something wrong or something wrong with my install until I found this issue here.

Just installed Grafana 6.7.2 and the latest clock panel 1.0.3 and the background color does not work.

**Comment by ryantxu** [comment]
Fixed in grafana master, and will be released in 7.0
