### ISSUE TITLE
Can't get to clock options

### ISSUE THREAD

**Issue by johnseekins** [grafana/clock-panel#7]
Every time I try to switch to the "Options" tab when creating a grafana clock object, it fails with the following error:

2016/04/22 15:16:48 [I] Completed 10.70.0.21 admin "GET /public/plugins/grafana-clock-panel/editor.html HTTP/1.1" 404 Not Found 19 bytes in 4684us

I used:
grafana-cli --pluginsDir . plugins install grafana-clock-panel

To install the plugin in the directory all my other panel plugins are stored in.

**Comment by daniellee** [comment]
Did it get installed properly? Is the editor.html file in the right directory? It should be located in your plugins directory, in the grafana-clock-panel/dist subdirectory.

**Comment by johnseekins** [comment]
Apologies for the late reply...

When I simply install the package, the folder looks like this:
[/usr/local/grafana/public/app/plugins/panel/grafana-clock-panel]: ls
dist  Gruntfile.js  LICENSE  package.json  plugin.json  README.md  src

And I get the following error when trying to load the clock panel:
2016/05/18 16:21:33 [I] Completed 10.70.0.21 admin "GET /public/app/plugins/panel/grafana-clock-panel/module.js HTTP/1.1" 404 Not Found 19 bytes in 4097us

So...I thought, well maybe I just need to copy dist/* to the current directory...
[/usr/local/grafana/public/app/plugins/panel/grafana-clock-panel]: ls dist/
clock_ctrl.js  clock_ctrl.js.map  css  editor.html  module.html  module.js  module.js.map  plugin.json  README.md  src
[/usr/local/grafana/public/app/plugins/panel/grafana-clock-panel]: sudo cp -rv dist/* .
`dist/clock_ctrl.js' -> `./clock_ctrl.js'
`dist/clock_ctrl.js.map' -> `./clock_ctrl.js.map'
`dist/css' -> `./css'
`dist/css/clock-panel.css' -> `./css/clock-panel.css'
`dist/editor.html' -> `./editor.html'
`dist/module.html' -> `./module.html'
`dist/module.js' -> `./module.js'
`dist/module.js.map' -> `./module.js.map'
`dist/plugin.json' -> `./plugin.json'
`dist/README.md' -> `./README.md'
`dist/src/img/clock_panel_logo.svg' -> `./src/img/clock_panel_logo.svg'
`dist/src/img/screenshot-clock-options.png' -> `./src/img/screenshot-clock-options.png'
`dist/src/img/screenshot-clocks.png' -> `./src/img/screenshot-clocks.png'
`dist/src/img/screenshot-showcase.png' -> `./src/img/screenshot-showcase.png'
`dist/src/img/countdown1.png' -> `./src/img/countdown1.png'
[/usr/local/grafana/public/app/plugins/panel/grafana-clock-panel]: sudo service grafana restart
OKopping Grafana Server ...                                [  OK  ]
Starting Grafana Server: .... OK
[/usr/local/grafana/public/app/plugins/panel/grafana-clock-panel]: ls
clock_ctrl.js  clock_ctrl.js.map  css  dist  editor.html  Gruntfile.js  LICENSE  module.html  module.js  module.js.map  package.json  plugin.json  README.md  src

Alright. Everything's loaded in the root of the folder. Now it will surely work!
2016/05/18 16:25:44 [I] Completed 10.70.0.21 admin "GET /public/plugins/grafana-clock-panel/editor.html HTTP/1.1" 404 Not Found 19 bytes in 4133us

So I'm lost. What am I doing wrong?

**Comment by johnseekins** [comment]
Futher notes, I am running the stable Grafana (3.0.1) on this host. All built-in plugins are fine.
The "piechart" plugin exhibits similar behavior, so I have to assume its something in how I'm installing the plugin. Maybe I should be bugging [grafana](https://github.com/grafana/grafana) instead?

**Comment by johnseekins** [comment]
Discovered my problem. I wasn't defining the "plugins" setting in custom.ini.
Adding that suddenly made grafana correctly detect those plugins.
