### ISSUE TITLE
The Clock Panel’s “Bg Color” Function doesn’t work

### ISSUE THREAD

**Issue by tghfly** [grafana/clock-panel#70]
Hi,
After Grafana v6.7.x,The Clock Panel’s “Bg Color” Function doesn’t work. But It’s normal in v6.6.2. May be a bug is here? Hope it can be confirmed and solved as soon as possible.
Thanks.

**Comment by lcoulet** [comment]
Hi, we noticed the same issue, this makes the panel unsuitable with Grafana 6.7.

**Comment by zoltanbedi** [comment]
This is a bug in Grafana not in the plugin. Follow https://github.com/grafana/grafana/issues/23306 for more info.

**Comment by ryantxu** [comment]
The clock panel was editing a css class that is no longer in grafana... this is now fixed in 7+ with clock 1.1+
