### ISSUE TITLE
Grafana 7 - Background not work

### ISSUE THREAD

**Issue by cicciopizza** [grafana/clock-panel#77]
I don't know if in previous versions it worked, but in grafana 7 if I set a background this is not displayed
![Selezione_114](https://user-images.githubusercontent.com/26459829/82571198-e5b32c80-9b82-11ea-9d9f-27960e74a835.png)

**Comment by senfomat** [comment]
Cannot reproduce in Grafana7 with a recent version:

![Bildschirmfoto 2020-05-23 um 15 28 11](https://user-images.githubusercontent.com/1766519/82731887-212c3300-9d0a-11ea-91d8-5edc2c105514.png)

**Comment by cicciopizza** [comment]
You're right, for some reason the clock-panel plugin was not updated correctly ... 
Now I managed to update it and it works 
Thanks
