### ISSUE TITLE
Migrating to v7 causes settings to be lost from previous panel config

### ISSUE THREAD

**Issue by briangann** [grafana/clock-panel#79]
An existing panel with this plugin in v6 looks like this:

![image](https://user-images.githubusercontent.com/7364245/82732076-9e3ab680-9cd0-11ea-9f34-a87fb3ea75a7.png)

with these settings:

![image](https://user-images.githubusercontent.com/7364245/82732095-b6aad100-9cd0-11ea-8cf7-7016f976cc75.png)

after upgrading to v7, the same panel looks like this:

![image](https://user-images.githubusercontent.com/7364245/82732115-d4783600-9cd0-11ea-989e-eba3c0831770.png)

and these are the settings (no changes to the panel json we made)

![image](https://user-images.githubusercontent.com/7364245/82732146-038ea780-9cd1-11ea-925d-5e606587ffe4.png)

**Comment by ryantxu** [comment]
hymmm -- not sure what is happening, if somethign changed (but it should not have!) we can munge things in:
https://github.com/grafana/clock-panel/pull/82/files#diff-28b01565cf8b54130a65fda8561a9392R4
