### ISSUE TITLE
Support actual Timezones

### ISSUE THREAD

**Issue by DomBlack** [grafana/clock-panel#8]
I've just setup this plugin, and the problem with it is it doesn't account for DST. So New York is currently -4, Tokyo is currently +9 and London is currently +1.

As the clock doesn't support actual timezones, when one of them changes, the dashboard will not update, leading to people assuming the wrong time!

**Comment by daniellee** [comment]
Yes, I agree. I tried to emphasize in the readme that for this early stage, the timezone support is very simple and basic. I'm planning to do this using [Moment JS Timezone](http://momentjs.com/timezone/) soon.

**Comment by cruiser607** [comment]
+1 :)

**Comment by johnseekins** [comment]
:+1:

**Comment by snc29590** [comment]
+1 

This would be a great feature to have.

**Comment by vozalexander** [comment]
+1 :)

**Comment by bmagistro** [comment]
I'm interested in this and willing to take a shot at a patch.  However, at the moment, I think I have everything setup right (grunt runs and doesn't throw any errors) but trying to add "include './moment-timezone';" causes things to error out.   If anyone has some insight on how to get past "TypeError: Cannot read property 'moment' of undefined at VERSION" that would be helpful.

**Comment by daniellee** [comment]
Yeah, I gave it a try a a month or two ago and couldn't get it to work.

**Comment by bmagistro** [comment]
@daniellee, thanks for the heads up.  I still have need for this so going to try and struggle through this.  JS dev isn't my strongest.  I've managed to make some progress, using <script> tags the timezone library works.  At the moment I am thinking that the timezone module cannot be included by a specific module with moment being included higher up...

**Comment by visago** [comment]
+1 for timezones !

**Comment by tardoe** [comment]
Also, not just timezones, but time in specific places. E.g. Australia/Sydney is UTC+10 in the winter and UTC+11 in the summer with daylight savings.

**Comment by nugget** [comment]
"Australia/Syndney" is a timezone, @tardoe.  That's exactly what this issue is requesting.

**Comment by ofbeaton** [comment]
+1 for timezones, plugin is useless for us without them!

**Comment by dboyd13** [comment]
+1
