### ISSUE TITLE
Background Color is not working

### ISSUE THREAD

**Issue by djryanj** [grafana/clock-panel#80]
Grafana version: v6.7.3 (a04ef6cefc) running in Docker image (pulled from grafana/grafana:6.7.3)
Panel plugin version: 1.0.3

Setting the background color seems to have no effect. Tried in FF 76.0.1, Chrome 83.0.4103.61, dark mode and light mode. 

![image](https://user-images.githubusercontent.com/33379396/83049677-bf6d1100-a008-11ea-9f38-65d2c016c142.png)

**Comment by ryantxu** [comment]
Fixed in 7 with v 1.1+

**Comment by djryanj** [comment]
@ryantxu are there any plans to backport the fix to 5-6/v1.0.3? I cannot upgrade on a whim.

**Comment by ryantxu** [comment]
no plans to update... the 5/6 versions modified css properties that don't exist.   Pull requests are welcome if you want to take a stab at it though
