### ISSUE TITLE
Refresh on sync not available after upgrade to Grafana 7.0.1

### ISSUE THREAD

**Issue by jramst** [grafana/clock-panel#81]
Before 7.x it was possible to update the clock only on dashboard refresh. It is even still mentioned in your README.md

Since upgrading to Grafana 7.0.1, our clocks are showing current time, instead of latest refresh time.

UPDATE: Tried to downgrade the plugin to 1.0.3 together with Grafana 7.0.1, but the clock does not sync correctly then either, even if the sync option appears.

**Comment by jramst** [comment]
Any update on when the pull request might be approved and the bug fixed?

**Comment by jramst** [comment]
I would like to ask again, when can we expect a fix on this issue?

**Comment by herbit** [comment]
My temporary solution to this is displaying the time stamp from the last entry in the data base (influxDB).

**Comment by ryan-miles** [comment]
Herbit - what influxDB query are you using to display a timestamp for the last database entry?

**Comment by herbit** [comment]
I just queried my table like this and selected "Time" in the Grafana Stat panel (Settings Panel/Display/Fields)
`SELECT "temperature" FROM "temperature" WHERE $timeFilter`

**Comment by ryan-miles** [comment]
Great - thank you for your  help!
