### ISSUE TITLE
Add ability to utilize query value on clock-panel

### ISSUE THREAD

**Issue by jordanpurinton** [grafana/clock-panel#84]
Instead of having to set the countdown clock manually, our team has a use case for utilizing a query value for the clock-panel, but seemingly there isn't a way to do this currently. Would be interested to know what the team thinks about the feasibility of this?

**Comment by wgheath255** [comment]
I have a use for this setup option as well.  I had thought that I might be able to set the countdown clock value using a variable, but that does not work either.  Setting it by query would be a great option.

**Comment by carlosag012** [comment]
Add countdown from custom variable, please.

Thanks

**Comment by ManishPhulwar** [comment]
We do have the similar requirement where countdown is required based on the timestamp/duration returned from the query.
Also if it can take value from Custom variable to set the countdown time.

**Comment by kke** [comment]
I'd like to show a timer displaying time elapsed since the last timestamp of data. Our LoRA sensors sometimes miss packets and it's hard to know if you're looking at a measurement from 9 minutes or 2 seconds ago.

**Comment by Danconnolly** [comment]
Does anyone know how to do this? This exactly matches what I need.
