### ISSUE TITLE
"Error loading: grafana-clock-panel" on Grafana 7.0.3

### ISSUE THREAD

**Issue by caranu** [grafana/clock-panel#85]
The clock-panel did not work after upgrading my Docker image to grafana/grafana:7.0.3 from 6.7. The Panel displayed an error message "Error loading: grafana-clock-panel".
The plugin list panel showed  Clock v1.1.1. After switching back to Grafana 6.7.4 the Clock v1.0.3 works fine again. Any ideas?

**Comment by marcusolsson** [comment]
I tried running the latest version of the plugin, v1.1.1, on 7.0.3 which worked. Did you ever get around this?

**Comment by caranu** [comment]
I am still running 6.7.4. 
I'm afraid it might be my Docker volume. I have /var/lib/grafana mounted as a volume. During the update I only pointed to the new image. If I ever try again, I'll try it with a fresh volume.

**Comment by marcusolsson** [comment]
Thanks for taking the time to respond to this. If you decide to try it again, please note that versions >=1.1.0 requires at least Grafana 7.0 or later. I'm closing this issue for now, but feel free to add to it should you try again.
