### ISSUE TITLE
Background color picker invisible

### ISSUE THREAD

**Issue by rvdheij** [grafana/clock-panel#86]
The color picker for the clock background is apparently initialized with the current background color (black in my case) which means that the dot in the color picker options menu is invisible. It took me a few hours to realize it's actually there.

I understand the UI approach to show the current selection in the color picker, but in that case the background for that dialogue should be of a contrasting color. It may be a general UI issue to solve with a contrasting line around the colored dot.

While you're at it, I would love to see a color picker for the font color as well.

**Comment by rvdheij** [comment]
When you're at it... how about a transparent background and contrasting font (so it will nicely work with both dark and light theme)

**Comment by Steve-dG** [comment]
Same issue.
I'm using the light theme and the clock is just a big black box with in a faintly very dark grey color a clock.

I've set the background to transparent, but the colors should just follow the UI Theme by default.
