### ISSUE TITLE
Background won't work with Grafana 8.0.0-beta1

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/clock-panel#92]
Background is always grey

**Comment by Rushmed** [comment]
Can confirm, backgoud always grey. Not editable.

**Comment by UlrichThiess** [comment]
The bug is still present in the final version 8.

The background can be set with the help of the "Boom Theme" plugin.

.css-1ge7kgp
   {background-color: inherit! important; }

**Comment by Rushmed** [comment]
Tried 
![image](https://user-images.githubusercontent.com/59259796/121400074-6ba14180-c957-11eb-82a9-3bf03b42afbe.png)
without success.

**Comment by UlrichThiess** [comment]
It is important that "Boom Theme" is positioned before the plug-in.

 

 

You can see it here: https://www.zoomsoft.de/grafana

 

Ulrich

 

Von: Rushmed ***@***.***>
Antworten an: grafana/clock-panel ***@***.***>
Datum: Mittwoch, 9. Juni 2021 um 19:19
An: grafana/clock-panel ***@***.***>
Cc: Ulrich Thiess ***@***.***>, Author ***@***.***>
Betreff: Re: [grafana/clock-panel] Background won't work with Grafana 8.0.0-beta1 (#92)

 

Tried

without success.

**Comment by Rushmed** [comment]
Solved it using your solution, thanks!

**Comment by jackw** [comment]
Fixed in https://github.com/grafana/clock-panel/releases/tag/v1.1.3
