### ISSUE TITLE
Grafana 8.0.0 Error Loading Plugin

### ISSUE THREAD

**Issue by ojwer** [grafana/clock-panel#95]
Installing V1.1.2 on Grafana 8.0.0 leads to "Error Loading Plugin".
Is there something I have to consider when installing? I Tried CLI and "Install and manage Plugins".

**Comment by EmilioD** [comment]
looks to affect upgraded instances too - clock plugin not working on 8.0.0

**Comment by EmilioD** [comment]
it looks like a clean uninstall/reinstall seems to mostly resolve it, using the CLI. Any display settings (ie font sizes) are lost but the plugin looks to work after a reinstall.

```
grafana-cli plugins remove grafana-clock-panel
systemctl restart grafana-server.service
grafana-cli plugins install grafana-clock-panel
systemctl restart grafana-server.service
```

**Comment by ojwer** [comment]
Restarting container after removing and after installing didn't solve the problem for me in an container environment.

**Comment by Yanonix** [comment]
It resolves for me (i'm not using a container environment), except the gray background (from #92) and the text not verticaly centered

**Comment by Monklite** [comment]
> It resolves for me (i'm not using a container environment), except the gray background (from #92) and the text not verticaly centered

Same issue for me. On 1.1.3 but still have the grey background.

**Comment by ojwer** [comment]
V1.1.3 works for me now on Grafana 8.1.2.

**Comment by Davidkramer1999** [comment]
If you get this error just rebuild the Docker container with docker compose up --build
