### ISSUE TITLE
make countdown timer more flexible

### ISSUE THREAD

**Issue by zuchka** [grafana/clock-panel#99]
see this thread on the forum.

https://community.grafana.com/t/semi-flexible-countdown/46243

> Is there a way to integrate a more flexible countdown into Grafana? I am currently using the clock module but the countdown needs to be set to an end time and date. Is it possible to count down every day to 2pm?

**Comment by zuchka** [comment]
potentially resolved [with this PR](https://github.com/grafana/clock-panel/pull/98)?

**Comment by gigillo73** [comment]
Hi. I would extract a value from a MySQL database; if this value is not null, I would use it to start the countdown. The use case is referred to the load control at home. My device read the power from the meter and receive the seconds before the switch off. I write this value into a MySQL database. I need to show this countdown (tipically 2 hours or 2 minutes) on the grafana clock panel . Thanks.
